### ISSUE TITLE
multi_level_map_server: invalid dependency on bwi_tools

### ISSUE THREAD

**Issue by jack-oquin** [utexas-bwi/multi_level_map#9]
This is an upward dependency, so it prevents MLM from being released.

ref: https://github.com/utexas-bwi/multi_level_map/blob/master/multi_level_map_server/nodes/multi_level_map_server#L5

**Comment by jack-oquin** [comment]
@piyushk: Why was resolver moved from MLM to bwi_tools in c3749e04804870ac1530880d67bf97ce57a6f88d That seems to be part of the problem, causing a dependency cycle.

I think those low-level services need to be moved back into MLM and removed from bwi_tools.

**Comment by jack-oquin** [comment]
@piyushk: looks like the original bug happened in 74221145533f50f10fcda5e7f31675e598fc4f32.

That's just wrong. (If you use ``catkin build`` instead of ``catkin_make`` this would have been found and fixed long ago.)

**Comment by jack-oquin** [comment]
@piyushk: should I move ``mapper.py`` and ``resource_resolver.py`` from ``bwi_tools`` to here (along with whatever other modules they depend on)?

**Comment by piyushk** [comment]
@jack-oquin: This is going to be tricky. I missed the cyclic repository dependency. resource_resolver.py and mapper.py are probably used elsewhere in the code, and furthermore resource_resolver.py has nothing to do with multi_level_map_utils, so it should not be used here.

The correct solution is to move bwi_tools to it's own separate repo/release, since it does not depend on anything else in our code base. That way, nothing will break.

**Comment by jack-oquin** [comment]
Ouch! We don't want more repositories.

How about moving the multi-level map packages into bwi_common? Do you think anyone else actually uses it?

**Comment by piyushk** [comment]
Yes. That would work! Even if someone else uses it (which I doubt), it should be fine.

**Comment by jack-oquin** [comment]
It may not be necessary to move all of them. Only the server has this direct dependency. 

I'll check whether the other packages depend on the server.

**Comment by piyushk** [comment]
I see. I would prefer moving all if we move the server though.

**Comment by jack-oquin** [comment]
Yeah. Better to reduce the number of repositories we have to maintain and release.
